import type { MergeHunk, MergePrecision } from '../lib/merge'
import {
  DIFF_MERGE_TAB_STORAGE_PREFIX,
  PRECISION_PHASE_GUARD,
  SUB_TAB_LABELS,
  createDiffMergeNavigationKeyHandler,
  diffMergeComponentResponsibilities,
  diffMergeViewDesign,
  isDiffMergeDevelopmentEnvironment,
  planDiffMergeSubTabs,
  planDiffMergeView,
  resolveDiffMergeStoredTab,
  type DiffMergeNavigationKeyEvent,
  type DiffMergeNavigationKeyHandler,
  type DiffMergeNavigationKeyHandlerOptions,
  type DiffMergePaneSpec,
  type DiffMergePaneTransition,
  type DiffMergeQueueCommandPayload,
  type DiffMergeSubTabKey,
  type DiffMergeSubTabPlan,
  type DiffMergeTabKey,
  type DiffMergeTabSpec,
  type DiffMergeTabStorage,
  type DiffMergeViewDesign,
  type DiffMergeViewPlan,
  type MergeDecisionEvent,
  type PrecisionPhaseGuard,
  type QueueMergeCommand,
} from '../lib/merge/diffMergePlan'

export type { MergeHunk, MergePrecision }

export {
  DIFF_MERGE_TAB_STORAGE_PREFIX,
  PRECISION_PHASE_GUARD,
  SUB_TAB_LABELS,
  createDiffMergeNavigationKeyHandler,
  diffMergeComponentResponsibilities,
  diffMergeViewDesign,
  isDiffMergeDevelopmentEnvironment,
  planDiffMergeSubTabs,
  planDiffMergeView,
  resolveDiffMergeStoredTab,
}

export type {
  DiffMergeNavigationKeyEvent,
  DiffMergeNavigationKeyHandler,
  DiffMergeNavigationKeyHandlerOptions,
  DiffMergePaneSpec,
  DiffMergePaneTransition,
  DiffMergeQueueCommandPayload,
  DiffMergeSubTabKey,
  DiffMergeSubTabPlan,
  DiffMergeTabKey,
  DiffMergeTabSpec,
  DiffMergeTabStorage,
  DiffMergeViewDesign,
  DiffMergeViewPlan,
  MergeDecisionEvent,
  PrecisionPhaseGuard,
  QueueMergeCommand,
}
