name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Configure pnpm store
        run: pnpm config set store-dir .pnpm-store

      - name: Ensure lockfile
        run: |
          if [ ! -f pnpm-lock.yaml ]; then
            pnpm install --lockfile-only
          fi

      - name: Install dependencies for SBOM
        run: pnpm install --frozen-lockfile

      - name: Install Syft CLI
        uses: anchore/sbom-action/download-syft@v0
        with:
          syft-version: latest

      - name: Generate SBOM
        run: |
          set -euo pipefail
          syft dir:. --scope all-layers -o cyclonedx-json=sbom.json 2>&1 | tee sbom.log

      - name: Upload SBOM artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
          if-no-files-found: error

      - name: Upload SBOM log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: sbom-log
          path: sbom.log
          if-no-files-found: ignore

  audit:
    needs:
      - sbom
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare pnpm
        run: corepack prepare pnpm@9.12.3 --activate

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Ensure lockfile
        run: |
          if [ ! -f pnpm-lock.yaml ]; then
            pnpm install --lockfile-only
          fi

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run pnpm audit
        run: pnpm audit --audit-level=moderate

      - name: Install osv-scanner
        run: |
          set -euo pipefail
          curl -sSfL https://raw.githubusercontent.com/google/osv-scanner/main/scripts/install.sh \
            | sh -s -- -b "$HOME/.local/bin"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Run osv-scanner
        run: osv-scanner --lockfile=pnpm-lock.yaml --format json --output audit-report.json

      - name: Upload audit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: audit-report
          path: audit-report.json
          if-no-files-found: error

  license:
    needs:
      - sbom
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare pnpm
        run: corepack prepare pnpm@9.12.3 --activate

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Ensure lockfile
        run: |
          if [ ! -f pnpm-lock.yaml ]; then
            pnpm install --lockfile-only
          fi

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Verify licenses
        run: pnpm -s license:check

      - name: Upload license reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: license-artifacts
          path: |
            license-report.json
            license-summary.json
          if-no-files-found: error

  build:
    needs:
      - sbom
      - license
      - quality
      - audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare pnpm
        run: corepack prepare pnpm@9.12.3 --activate

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Ensure lockfile
        run: |
          if [ ! -f pnpm-lock.yaml ]; then
            pnpm install --lockfile-only
          fi

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: |
          set -euo pipefail
          pnpm --reporter ndjson -s build |& tee build.log

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist
          if-no-files-found: ignore

      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log
          if-no-files-found: ignore

  quality:
    needs:
      - sbom
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - suite: lint
            command: pnpm -s lint
            collect_failures: false
          - suite: typecheck
            command: pnpm -s typecheck
            collect_failures: false
          - suite: autosave
            command: pnpm -s test:autosave
            collect_failures: true
          - suite: merge
            command: pnpm -s test:merge
            collect_failures: true
          - suite: cli
            command: pnpm -s test:cli
            collect_failures: true
          - suite: collector
            command: pnpm -s test:collector
            collect_failures: true
          - suite: telemetry
            command: pnpm -s test:telemetry
            collect_failures: true
    name: Quality (${{ matrix.suite }})

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare pnpm
        run: corepack prepare pnpm@9.12.3 --activate

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Ensure lockfile
        run: |
          if [ ! -f pnpm-lock.yaml ]; then
            pnpm install --lockfile-only
          fi

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ${{ matrix.suite }} suite
        id: run_suite
        continue-on-error: true
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p logs
          ${{ matrix.command }} |& tee "logs/${{ matrix.suite }}.log"

      - name: Extract failed test output
        if: steps.run_suite.outcome == 'failure' && matrix.collect_failures
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p logs
          grep -E ':[0-9]+:[0-9]+: |not ok|FAIL|Error' "logs/${{ matrix.suite }}.log" > "logs/${{ matrix.suite }}-failures.log" || true

      - name: Upload suite logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: quality-${{ matrix.suite }}
          path: |
            logs/${{ matrix.suite }}.log
            logs/${{ matrix.suite }}-failures.log
          if-no-files-found: ignore

      - name: Report suite failure
        if: steps.run_suite.outcome == 'failure'
        shell: bash
        run: |
          set -euo pipefail
          echo "::group::${{ matrix.suite }} suite failure log"
          if [[ -f "logs/${{ matrix.suite }}.log" ]]; then
            cat "logs/${{ matrix.suite }}.log"
          else
            echo "suite log not found"
          fi
          echo "::endgroup::"
          if [[ -f "logs/${{ matrix.suite }}-failures.log" ]]; then
            while IFS= read -r line; do
              if [[ -n "$line" ]]; then
                echo "::error::${line}"
              fi
            done < "logs/${{ matrix.suite }}-failures.log"
          fi
          exit 1

  reports:
    needs:
      - quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare pnpm
        run: corepack prepare pnpm@9.12.3 --activate

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Ensure lockfile
        run: |
          if [ ! -f pnpm-lock.yaml ]; then
            pnpm install --lockfile-only
          fi

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test with coverage
        run: |
          set -euo pipefail
          rm -rf coverage
          pnpm -s test:coverage

      - name: Generate JUnit report
        run: |
          set -euo pipefail
          mkdir -p reports
          pnpm test -- --test-reporter junit --test-reporter-destination reports/junit.xml

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
          if-no-files-found: error

      - name: Upload junit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: reports/junit.xml
          if-no-files-found: error

  golden:
    needs:
      - build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare pnpm
        run: corepack prepare pnpm@9.12.3 --activate

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Ensure lockfile
        run: |
          if [ ! -f pnpm-lock.yaml ]; then
            pnpm install --lockfile-only
          fi

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run golden comparison
        id: golden
        continue-on-error: true
        run: |
          set -euo pipefail
          rm -rf runs golden-diff.txt golden.log
          pnpm -s golden:ci |& tee golden.log

      - name: Upload golden artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: golden-artifacts
          path: |
            golden.log
            golden-diff.txt
            runs
          if-no-files-found: ignore

      - name: Assert golden comparison passed
        if: steps.golden.outcome == 'failure'
        run: exit 1
